### ISSUE TITLE
make file has erroneous params

### ISSUE THREAD

**Issue by ab927** [DenysTT/harvest_feeder#1]
in make file

	docker run --rm -e HARVEST_ACCESS_TOKEN=$(HARVEST_TOKEN) -e HARVEST_ACCOUNT_ID=$(ACCOUNT_ID) --name feeder $(image)

 should be:

docker run --rm -e HARVEST_ACCESS_TOKEN=$(HARVEST_ACCESS_TOKEN) -e HARVEST_ACCOUNT_ID=$(HARVEST_ACCOUNT_ID) --name feeder $(image)

**Comment by DenysTT** [comment]
fixed, thanks
